services:
  - type: web
    name: hehe-app-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hehe-db
          property: connectionString

databases:
  - name: hehe-db
    databaseName: hehe
    user: hehe
    plan: free 